[project]
name = "gitcraft"
version = "0.1.0"
description = "A practical, readable Git reference for everyday workflows and long-term mastery."
readme = "README.md"
authors = [
    { name = "saqibbedar", email = "chandio.saqib.m@gmail.com" }
]
requires-python = ">=3.14"
dependencies = [
    "zensical>=0.0.58",
]

[project.scripts]
start = "gitcraft:main"

[build-system]
requires = ["uv_build>=0.12.5,<0.13.0"]
build-backend = "uv_build"

[dependency-groups]
dev = []
